export const ROLE_DISPLAY_NAMES: Record<string, string> = {
  system_administrator: "System Administrator",
  director: "Director",
  house_master: "House Master",
  deputy_master: "Deputy House Master",
  medical: "Medical Staff",
  kitchen: "Kitchen Staff",
  parent: "Boarder Parent",
  boarder: "Boarder",
  support_staff: "Support Staff",
};

export const ROLE_PANELS = {
  system_administrator: [
    "dashboard",
    "users",
    "rooms",
    "medical",
    "kitchen",
    "attendance",
    "leave",
    "discipline",
    "wellbeing",
    "events",
    "config",
    "audit",
    "maintenance",
    "messaging",
    "mentor",
  ],
  director: [
    "dashboard",
    "users",
    "rooms",
    "medical",
    "kitchen",
    "attendance",
    "leave",
    "discipline",
    "wellbeing",
    "events",
    "maintenance",
    "messaging",
  ],
  house_master: [
    "dashboard",
    "rooms",
    "attendance",
    "leave",
    "discipline",
    "wellbeing",
    "messaging",
  ],
  deputy_master: [
    "dashboard",
    "rooms",
    "attendance",
    "leave",
    "discipline",
    "wellbeing",
    "messaging",
  ],
  medical: ["dashboard", "medical", "messaging", "wellbeing"],
  kitchen: ["dashboard", "kitchen", "messaging"],
  parent: ["dashboard", "leave", "wellbeing", "messaging"],
  boarder: ["dashboard", "leave", "wellbeing", "messaging"],
} as const;

export const ROLE_PERMISSIONS = {
  system_administrator: ["*"],
  director: ["manage_users", "manage_houses", "view_reports", "manage_events"],
  house_master: [
    "manage_attendance",
    "manage_discipline",
    "manage_leave",
    "manage_rooms",
  ],
  deputy_master: [
    "manage_attendance",
    "manage_discipline",
    "manage_leave",
    "manage_rooms",
  ],
  medical: ["manage_medical", "view_medical"],
  kitchen: ["manage_kitchen"],
  parent: ["view_child_info", "request_leave"],
  boarder: ["view_own_info", "request_leave"],
} as const;
